---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7

# https://docs.travis-ci.com/user/languages/ruby/#bundler-20
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile

matrix:
  exclude:
    - rvm: 2.3
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.7
      gemfile: gemfiles/4.2.gemfile

notifications:
  email: false
